#!/usr/bin/env bash

KERNEL_VERSION=5.19.10
KERNEL_VERSION_MAJOR=${KERNEL_VERSION%%.*}
case $KERNEL_VERSION in
	*.*.*) KERNEL_VERSION_MINOR=${KERNEL_VERSION%.*};;
	*.*) KERNEL_VERSION_MINOR=$KERNEL_VERSION;;
esac

PKGREL=0
BUILD_FLAVOR=edge
ABI_RELEASE=$KERNEL_VERSION-0-$BUILD_FLAVOR
INSTALL="zinstall dtbs_install"

OUTDIR=$(pwd)/output
SRC_FOLDER=$(pwd)/src
LINUX_FOLDER=$SRC_FOLDER/linux-$KERNEL_VERSION_MINOR
INITIAL_PWD=$(pwd)

